phoenix/discuss/web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser  # module plug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    # 會自動導到需要的分頁
    resources "/", TopicController
  end

  scope "/auth", Discuss do
    pipe_through :browser # Use the default browser stack

    get "/signout", AuthController, :signout

    # :request 自動被 plug Ueberauth module 定義了，所以我們不用定義。
    # 將原本 "/github" 改寫成 "/:provider" ，這樣就不單單只可以接收一種 route
    # 這一個是處理剛進來初始的 OAuth 要求
    get "/:provider", AuthController, :request   

    # 這一個處理從 github 返回的
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

phoenix/discuss/web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

phoenix/discuss/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <!-- CSS 連結 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Icon 連結 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <nav class="navy">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>  
            <li>
              <!--會有"github"，是因為 router 接收的 URL 是個原子-->
              <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %> 
        </ul>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html> 